// GENERATED BY HAND (minimal) – no build_runner needed
part of 'models.dart';

class BowlEntryAdapter extends TypeAdapter<BowlEntry> {
  @override final int typeId = 1;
  @override BowlEntry read(BinaryReader r) {
    r.readByte(); // fields count (ignored)
    return BowlEntry(
      name: r.read(),
      frequencyHz: r.read(),
      note: r.read(),
      cents: r.read(),
      createdAt: r.read(),
      memo: r.read(),
    );
  }
  @override void write(BinaryWriter w, BowlEntry obj) {
    w.writeByte(6);
    w.write(obj.name);
    w.write(obj.frequencyHz);
    w.write(obj.note);
    w.write(obj.cents);
    w.write(obj.createdAt);
    w.write(obj.memo);
  }
}

class BowlSetAdapter extends TypeAdapter<BowlSet> {
  @override final int typeId = 2;
  @override BowlSet read(BinaryReader r) {
    r.readByte();
    return BowlSet(
      title: r.read(),
      bowlIds: (r.read() as List).cast<int>(),
      createdAt: r.read(),
    );
  }
  @override void write(BinaryWriter w, BowlSet obj) {
    w.writeByte(3);
    w.write(obj.title);
    w.write(obj.bowlIds);
    w.write(obj.createdAt);
  }
}
